# Generated by Django 2.0.4 on 2018-04-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KurnikReplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('player1', models.CharField(max_length=20)),
                ('player2', models.CharField(max_length=20)),
                ('replay_date', models.CharField(max_length=10)),
                ('replay_time', models.CharField(max_length=8)),
                ('replay_round', models.CharField(max_length=3)),
                ('player1_elo', models.CharField(max_length=4)),
                ('player2_elo', models.CharField(max_length=4)),
                ('moves', models.TextField(blank=True, max_length=1000)),
                ('result', models.CharField(max_length=3)),
            ],
        ),
    ]
