# Generated by Django 2.0.4 on 2018-04-27 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scheme_access', models.CharField(choices=[('1', 'oficjalny'), ('2', 'publiczny'), ('3', 'prywatny')], max_length=1)),
                ('scheme_type', models.CharField(choices=[('1', 'obrona'), ('2', 'atak'), ('3', 'inne')], max_length=1)),
                ('description', models.TextField(blank=True, max_length=4000)),
                ('parent_dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_scheme_directory', to='schemes.SchemeDirectory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_directory_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
