# Generated by Django 2.0.4 on 2018-04-27 07:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schemes', '0002_schemedirectory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('elements', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('board', models.CharField(choices=[('0', 'normalne'), ('1', 'odwrócone')], max_length=1)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='schemes.SchemeDirectory')),
                ('replay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='schemes.KurnikReplay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
