# Generated by Django 2.0.4 on 2018-04-28 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schemes', '0003_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.CharField(choices=[('0', 'niesprawdzone'), ('1', 'sprawdzone')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReplayDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('replay_access', models.CharField(choices=[('2', 'publiczny'), ('3', 'prywatny')], max_length=1)),
                ('parent_dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_replay_directory', to='schemes.ReplayDirectory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_directory_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='replay',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vreplays', to='schemes.ReplayDirectory'),
        ),
        migrations.AddField(
            model_name='replay',
            name='replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kreplays', to='schemes.KurnikReplay'),
        ),
        migrations.AddField(
            model_name='replay',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vreplay_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
