# Generated by Django 2.0.4 on 2018-04-29 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schemes', '0004_auto_20180428_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('replay_access', models.CharField(choices=[('2', 'publiczny'), ('3', 'prywatny')], max_length=1)),
                ('moves', models.TextField(max_length=2000)),
                ('parent_replay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_kreplay', to='schemes.KurnikReplay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ureplay_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
