# Generated by Django 2.0.4 on 2018-04-30 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0005_userreplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='ureplay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treplays', to='schemes.UserReplay'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='ureplay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ureplays', to='schemes.UserReplay'),
        ),
    ]
