# Generated by Django 2.0.4 on 2018-05-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0008_auto_20180501_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
