# Generated by Django 2.0.4 on 2018-05-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0014_kurnikranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurnikranking',
            name='games',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kurnikranking',
            name='ranking',
            field=models.IntegerField(),
        ),
    ]
